version: '3.9'
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - 5454:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - 6000:6379
  nest-app:
    container_name: nest-app
    build:
      context: ./backend_app
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5000:5000
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
    environment:
      -POSTGRES_DB: "test"
      -POSTGRES_USER: "test"
      -POSTGRES_PASSWORD: "123456789"
    volumes:
#      - /app/server/node_modules
      - ./backend_app:/app/server
  react-app:
    container_name: react-app
    build:
      context: front_app
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - nest-app
    volumes:
#      - /app/client/node_modules
      - ./front_app:/app/client
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    depends_on:
      postgres:
        condition: service_started
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  pg-data:
    driver: local
  pgadmin-data:
    driver: local
